webapp/urls.py
from django.urls import path
from . import  views
app_name='webapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.details,name='details'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),
]

webprodect/urls.py
from django.contrib import admin
from django.urls import path,include

from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("webapp.urls"))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

webapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    img=models.ImageField(upload_to='gallery')
    desc=models.TextField()
    year=models.IntegerField()

    def __str__(self):
        return self.name

webapp/forms.py
from django import forms

from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','img','desc','year']

webapp/views.py
from django.shortcuts import redirect

from django.shortcuts import render
from django.http import HttpResponse
from .models import Movie
from . forms import MovieForm

# Create your views here.
def index(request):
   movie = Movie.objects.all()
   context={
       'movie_list' : movie
   }
   return render(request,'index.html',context)

def details(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,"details.html",{'movie' :movie})

def add_movie(request):
    if request.method=='POST':
        name=request.POST.get('name',)
        img = request.FILES['img']
        desc = request.POST.get('desc',)
        year = request.POST.get('year',)

        movie=Movie(name=name,img=img,desc=desc,year=year)
        movie.save()
        return redirect('/')

    return render(request,"add.html")


def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')

    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

templates/add.html
{% extends 'base.html'  %}
{% block body %}

<form action=" " method="post" enctype="multipart/form-data">
{% csrf_token %}
    <input type="text" name="name" placeholder="enter the movie name"> <br><br>
    <input type="file" name="img"><br><br>
    <textarea  name="desc" rows="4" cols="50" placeholder="description"></textarea><br><br>
    <input type="text" name="year" placeholder="enter the year"><br><br>
    <input type="submit">
</form>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <title>index</title>
</head>
<body style="background-color: aqua;">
<nav class="navbar navbar-dark bg-dark">
  <div class="container-md">
    <a class="navbar-brand" href="{% url 'webapp:index' %}">Movie Store</a>
  </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

templates/delete.html
{% extends 'base.html'  %}
{% block body %}

<form method="post">
    {% csrf_token%}

    <p><b>Are you want to delete ?</b></p>
    <input type="submit">


</form>
{% endblock %}

templates/details.html
{% extends 'base.html'  %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="text-center">
        <div class="rounded-3">
           <img src="{{movie.img.url}}" width="250" height="250"><br><br>
        </div>
            <div class="display-5">{{movie.name}}</div>
           <p class="blockquote"> {{movie.desc}}</p>
           <strong>Released year : {{movie.year}}</strong><br><br>
        <a class="btn btn-warning" href="{% url 'webapp:update' movie.id %}">update</a>
        <a class="btn btn-danger" href="{% url 'webapp:delete' movie.id%}">Delete</a>
        </div>
    </div>
</div>


{% endblock %}







<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Title</title>-->
<!--</head>-->
<!--<body>-->
<!--{% for i in movie_list %}-->
<!--{{i.desc}} >>>>> {{i.year}}-->
<!--{% endfor %}-->
<!--</body>-->
<!--</html>-->

templates/edit.html
{% extends 'base.html'  %}
{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token%}
    {{form.as_p}}
    <input type="submit">
</form>

{% endblock %}

templates/index.html
{% extends 'base.html'  %}
{% block body %}

<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-2">
            <div class="card" style="width: 12rem;">
                <img src="{{i.img.url}}" class="card-img-top" width="150px" height="300px">
                    <div class="card-body" style="color : black;">
                        <h5 class="card-title">{{i.name}}</h5>
                         <a href="{% url 'webapp:details' i.id %}" class="btn btn-warning">view Details</a>
                     </div>
            </div>
        {% endfor %}
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="d-flex justify-content-center"><a class="btn btn-primary" href="{% url 'webapp:add_movie' %}">Add Movie</a></div>
    </div>
</div>

{% endblock %}